### PR TITLE
Update list.txt

### PR DESCRIPTION
**Pull request by rkmtrials**
pubg lite
pubg
clash of kings
mobile legend

### CODE REVIEW

**Review by aishik212 — CHANGES_REQUESTED** [review]
recheck the games package name, they are all the same

**Comment by rkmtrials** [comment]
> recheck the games package name, they are all the same
koreeachi .... they are all same tencent

**Comment by aishik212** [comment]
pubg - com.tencent.ig
clash of kings - com.hcg.cok.gp
mobile legends - com.mobile.legends

**Comment by rkmtrials** [comment]
yes it changed now .... see screenshort

**Comment by aishik212** [comment]
latest commit kore request kor

**Review by aishik212 — DISMISSED** [review]

**Pull request closed without merging**
